version: '3.3'

services:
  db:
    image: postgres:11-alpine
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=AUTOMATIC_SUMMARIZER
      - POSTGRES_USER=user_as
      - POSTGRES_PASSWORD=abc123
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

  automatic_summarizer:
    build: .
    volumes:
      - ./config:/root/automatic_summarizer/config:ro
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db

volumes:
  postgres-data:
