version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_DATABASE=AUTOMATIC_SUMMARIZER
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_USER=user_as
      - MYSQL_PASSWORD=abc123
      - MYSQL_PORT=3306
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    restart: on-failure
    volumes:
      - ./config:/root/automatic_summarizer/config:ro
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db

volumes:
  mysql-data: