version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_DATABASE=AUTOMATIC_SUMMARIZER
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_USER=user_as
      - MYSQL_PASSWORD=docker123
      - MYSQL_PORT=3306
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    image: leandro2r/automatic_summarizer:1.1.0 
    restart: on-failure
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db

volumes:
  mysql-data: