version: '3.3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: on-failure
    env_file:
      - db.env
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    container_name: automatic_summarizer
    restart: on-failure
    build: .
    command: ["./run.sh"]
    env_file:
      - db.env
    volumes:
      - .:/automatic_summarizer
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

volumes:
  mysql-data: