# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='T\xedtulo')),
                ('file', models.FileField(upload_to=b'', verbose_name='Arquivo .PDF')),
                ('url', models.URLField(blank=True, default='http://', verbose_name='Reposit\xf3rio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
